#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS **PARTIALLY** GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 *
 * *NOTE*: keymap.json doesn't support key_combos which are added here
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_ortho_4x12(KC_Q, LGUI_T(KC_W), KC_E, KC_R, KC_T, KC_NO, KC_NO, KC_Y, KC_U, KC_I, RGUI(KC_O), KC_P, KC_A, KC_S, KC_D, KC_F, KC_G, KC_NO, KC_NO, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_Z, LALT_T(KC_X), LCTL_T(KC_C), KC_V, KC_B, KC_NO, KC_NO, KC_N, KC_M, RCTL_T(KC_COMM), RALT_T(KC_DOT), KC_SLSH, KC_NO, KC_NO, KC_NO, MO(1), LSFT_T(KC_SPC), KC_NO, KC_NO, KC_RSFT, MO(2), KC_NO, KC_NO, KC_NO),
    [1] = LAYOUT_ortho_4x12(KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_NO, KC_NO, KC_CIRC, KC_AMPR, KC_ASTR, KC_PIPE, KC_NO, KC_LBRC, KC_RBRC, KC_LPRN, KC_RPRN, KC_LCBR, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_RCBR, KC_NO, KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, MO(3), KC_NO, KC_NO, KC_NO),
    [2] = LAYOUT_ortho_4x12(KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_NO, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PLUS, KC_4, KC_5, KC_6, KC_MINS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_EQL, KC_1, KC_2, KC_3, KC_UNDS, KC_NO, KC_NO, KC_NO, MO(3), KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO),
    [3] = LAYOUT_ortho_4x12(QK_BOOT, DB_TOGG, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F7, KC_F8, KC_F9, KC_F10, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_F11, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_F12, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

#ifdef COMBO_ENABLE
const uint16_t PROGMEM combo_esc[] =     {KC_Q, KC_W,    COMBO_END};
const uint16_t PROGMEM combo_grave[] =   {KC_W, KC_E,    COMBO_END};
const uint16_t PROGMEM combo_tilde[] =   {KC_R, KC_T,    COMBO_END};
const uint16_t PROGMEM combo_space[] =   {KC_D, KC_F,    COMBO_END};
const uint16_t PROGMEM combo_tab[] =     {KC_F, KC_G,    COMBO_END};
const uint16_t PROGMEM combo_ctrl_c[] =  {KC_X, KC_C,    COMBO_END};
const uint16_t PROGMEM combo_ctrl_v[] =  {KC_C, KC_V,    COMBO_END};
const uint16_t PROGMEM combo_cw_rght[] = {KC_V, KC_B,    COMBO_END};
const uint16_t PROGMEM combo_bsls[] =    {KC_Y, KC_U,    COMBO_END};
const uint16_t PROGMEM combo_quot[] =    {KC_I, KC_O,    COMBO_END};
const uint16_t PROGMEM combo_dquo[] =    {KC_O, KC_P,    COMBO_END};
const uint16_t PROGMEM combo_bspc[] =    {KC_H, KC_J,    COMBO_END};
const uint16_t PROGMEM combo_ent[] =     {KC_J, KC_K,    COMBO_END};
const uint16_t PROGMEM combo_coln[] =    {KC_L, KC_SCLN, COMBO_END};
const uint16_t PROGMEM combo_cw_left[] = {KC_N, KC_M,    COMBO_END};

combo_t key_combos[] = {
  COMBO(combo_esc,     KC_ESC),
  COMBO(combo_grave,   KC_GRV),
  COMBO(combo_tilde,   KC_TILD),
  COMBO(combo_space,   KC_SPC),
  COMBO(combo_tab,     KC_TAB),
  COMBO(combo_ctrl_c,  LSFT(KC_C)),
  COMBO(combo_ctrl_v,  LSFT(KC_V)),
  COMBO(combo_cw_rght, LSG(KC_RGHT)),
  COMBO(combo_bsls,    KC_BSLS),
  COMBO(combo_quot,    KC_QUOT),
  COMBO(combo_dquo,    KC_DQUO),
  COMBO(combo_bspc,    KC_BSPC),
  COMBO(combo_ent,     KC_ENT),
  COMBO(combo_coln,    KC_COLN),
  COMBO(combo_cw_left, LSG(KC_LEFT)),
};
#endif
